---
AWSTemplateFormatVersion: "2010-09-09"
Description: GitLab CI - OIDC IDP and associated Role for Resource Deployment

Parameters:
  GroupName:
    Type: String
    Description: (CASE SENSITIVE) This is the GitLab group name. If using multiple groups, list the full path for the group(s)
    Default: ""

  RoleName:
    Type: String
    Description: Name the Role
    Default: ""

  RepositoryName:
    Type: String
    Description: The repo(s) these roles will have access to. (Use * for all repos within the group)
    Default: "*"

  BranchName:
    Type: String
    Description: The branch to allow automation to run against.
    Default: "*"

Resources:
  IdpGitLabOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://gitlab.com
      ClientIdList:
        - https://gitlab.com
      ThumbprintList:
        - b3dd7606d2b5a8b4a13771dbecc9ee1cecafa38a
      Tags:
        - Key: Name
          Value: !Sub ${RoleName}-OIDC-Provider

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${RoleName}-Deploy
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/gitlab.com
            Condition:
              StringLike:
                #gitlab.com:sub: !Sub project_path:${GroupName}*:*
                gitlab.com:sub: !Sub project_path:${GroupName}/${RepositoryName}:ref_type:branch:ref:${BranchName}
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSCloudFormationFullAccess

Outputs:
  IdpGitLabOidc:
    Description: "ARN of GitLab OIDC Provider"
    Value: !GetAtt IdpGitLabOidc.Arn
    Export:
      Name: !Sub ${RoleName}-Arn

  RoleARN:
    Description: "ARN of Deploy Access Role for GitLab CI"
    Value: !GetAtt Role.Arn
    Export:
      Name: !Sub ${RoleName}-Gitlab-CI
